### ISSUE TITLE
Build fails after upgrading nixpkgs unstable channel past 32aa10f0972

### ISSUE THREAD

**Issue by psanford** [tpwrules/nixos-m1#16]
After updating the nixpkgs (unstable) channel, building uboot started to fail:
```
error: builder for '/nix/store/msjicb8q80namdk5nr2a336dm5ayb6yb-lzip-aarch64-unknown-linux-gnu-1.23.drv' failed with exit code 2
error: 6 dependencies of derivation '/nix/store/fj8331h736lfk36fz43l6san1qqbn7na-gnutls-aarch64-unknown-linux-gnu-3.7.6.drv' failed to build
error: 3 dependencies of derivation '/nix/store/7lf1sf3lsyhpn79x0zkhsix455xprdbw-uboot-apple_m1_defconfig-aarch64-unknown-linux-gnu-2022.07_rc100.asahi3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k80xg84vcmb0q151yf7ywqqhbpdmbpim-boot.bin.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fjhfvamfixpbd2xylq8p687saklv165n-grub-config.xml.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1i6xjvi88rk6pnd6lagzwlqv49zcy35r-install-grub.sh.drv' failed to build
```

I bisected nixpkgs down to this commit: [ubootTools: Fix after update of uboot to 2022.07
](https://github.com/NixOS/nixpkgs/commit/32aa10f0972b9a8bc8ad6e6bc831cca4e4789885). 

Overriding `buildInputs` to be empty fixes it for me: `buildInputs = [ ];` Not sure if that is the "correct" solution though.

**Comment by tpwrules** [comment]
Looks like this is because I am using `pkgsCross.aarch64-multiplatform.buildUBoot` even on native aarch64. Lzip was introduced as a dependency in that commit and it is not happy with that. I'll have to revise the cross logic there, but your patch will work just fine for now.

**Comment by tpwrules** [comment]
Fixed in the latest release, thank you again for finding and bisecting this!
