### ISSUE TITLE
KDE + Wayland + experimental GPU driver

### ISSUE THREAD

**Issue by bkchr** [tpwrules/nixos-m1#45]
Hey did someone get this configuration working? 

Using X11 with the experimental GPU driver works, but wayland fails. It starts, but hangs and I couldn't yet find any indication on what is wrong. I tried to remove almost everything from my config and to only add KDE, but it didn't helped.

**Comment by tpwrules** [comment]
Thanks for discovering, reporting, and providing a solution for this. It is fixed now.

I initially hoped we could mix Mesa versions like this but it's clear now that's not possible.
